# Form implementation generated from reading ui file 'Data/tournament.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tournament(object):
    def setupUi(self, Tournament):
        Tournament.setObjectName("Tournament")
        Tournament.resize(800, 600)
        self.menubar = QtWidgets.QMenuBar(parent=Tournament)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.actionLoad = QtGui.QAction(parent=Tournament)
        self.actionLoad.setObjectName("actionLoad")
        self.actionReset = QtGui.QAction(parent=Tournament)
        self.actionReset.setObjectName("actionReset")
        self.centralWidget = QtWidgets.QWidget(parent=Tournament)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topButtons = QtWidgets.QHBoxLayout()
        self.topButtons.setObjectName("topButtons")
        self.loadButton = QtWidgets.QPushButton(parent=self.centralWidget)
        self.loadButton.setObjectName("loadButton")
        self.topButtons.addWidget(self.loadButton)
        self.resetButton = QtWidgets.QPushButton(parent=self.centralWidget)
        self.resetButton.setObjectName("resetButton")
        self.topButtons.addWidget(self.resetButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topButtons.addItem(spacerItem)
        self.verticalLayout.addLayout(self.topButtons)
        self.tournamentView = QtWidgets.QGraphicsView(parent=self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tournamentView.sizePolicy().hasHeightForWidth())
        self.tournamentView.setSizePolicy(sizePolicy)
        self.tournamentView.setObjectName("tournamentView")
        self.verticalLayout.addWidget(self.tournamentView)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Tournament)
        QtCore.QMetaObject.connectSlotsByName(Tournament)

    def retranslateUi(self, Tournament):
        _translate = QtCore.QCoreApplication.translate
        Tournament.setWindowTitle(_translate("Tournament", "Tournament"))
        self.menuFile.setTitle(_translate("Tournament", "File"))
        self.actionLoad.setText(_translate("Tournament", "Load"))
        self.actionLoad.setStatusTip(_translate("Tournament", "Load tournament file"))
        self.actionReset.setText(_translate("Tournament", "Reset"))
        self.actionReset.setStatusTip(_translate("Tournament", "Reset tournament"))
        self.loadButton.setText(_translate("Tournament", "Load"))
        self.resetButton.setText(_translate("Tournament", "Reset"))
